# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ching-Ting Lin
email: eric20706@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Student studies CS in NYCU.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ericlin7322.github.io" # the base hostname & protocol for your site
twitter_username: lineric0
github_username:  ericlin7322
instagram_username: wow0.0wow
linkedin_username: ching-ting-lin-6b1365259

# Build settings
# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
